### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by frederikhors** [wingertge/artemis#62]
The idea behind this is all what I was wondering and what I think is needed in the world, for a better world.

Is this abandoned? And why if so?

**Comment by wingertge** [comment]
It is abandoned, because it ended up being too complex for a personal side project and the code quickly became unmaintainable as the feature set grew. I would have to do pretty much a full rewrite to fix that and have neither the time not motivation for that at the moment.
I've kind of moved on from GraphQL to the `trpc` style of automatically type checked server functions.

**Comment by frederikhors** [comment]
Is TRPC a thing in Rust ecosystem?

**Comment by wingertge** [comment]
> Is TRPC a thing in Rust ecosystem?

It sort of is. I built a minimal version working for axum that would work with any frontend (or any Rust application really) [here](https://github.com/wingertge/wrpc), and `leptos` has it built in as server functions. The leptos one is certainly more elegant than mine.
